// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xyz
{
    [XyzResourceType("xyz:index:Vpc")]
    public partial class Vpc : Pulumi.ComponentResource
    {
        /// <summary>
        /// List of IDs for the VPC's EKS Control Plane subnets.
        /// </summary>
        [Output("controlPlaneSubnetIds")]
        public Output<ImmutableArray<string>> ControlPlaneSubnetIds { get; private set; } = null!;

        /// <summary>
        /// List of IDs for the VPC's private subnets.
        /// </summary>
        [Output("privateSubnetIds")]
        public Output<ImmutableArray<string>> PrivateSubnetIds { get; private set; } = null!;

        /// <summary>
        /// List of IDs for the VPC's public subnets.
        /// </summary>
        [Output("publicSubnetIds")]
        public Output<ImmutableArray<string>> PublicSubnetIds { get; private set; } = null!;

        /// <summary>
        /// The VPC resource.
        /// </summary>
        [Output("vpcResource")]
        public Output<Pulumi.Aws.Ec2.Vpc> VpcResource { get; private set; } = null!;


        /// <summary>
        /// Create a Vpc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Vpc(string name, VpcArgs args, ComponentResourceOptions? options = null)
            : base("xyz:index:Vpc", name, args ?? new VpcArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class VpcArgs : Pulumi.ResourceArgs
    {
        [Input("availabilityZoneNames", required: true)]
        private InputList<string>? _availabilityZoneNames;

        /// <summary>
        /// The list of target availability zone names.
        /// </summary>
        public InputList<string> AvailabilityZoneNames
        {
            get => _availabilityZoneNames ?? (_availabilityZoneNames = new InputList<string>());
            set => _availabilityZoneNames = value;
        }

        /// <summary>
        /// The IP CIDR block for the dedicated EKS VPC network.
        /// </summary>
        [Input("cidrBlock", required: true)]
        public Input<string> CidrBlock { get; set; } = null!;

        /// <summary>
        /// The name for the deployed EKS cluster.
        /// </summary>
        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        [Input("tags", required: true)]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags to apply to all child resources.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public VpcArgs()
        {
        }
    }
}
